### PR TITLE
Import export example - Refactoring & JUnit Test

### PR DESCRIPTION
**Pull request by DallonTG**
We have talked about wanting to include all of the included example programs as part of the tests that are run when RS2 is built. For this to be done, the example programs have to be refactored a bit (since they are mostly just main() methods).

This pull request includes a refactored ImportExportExample and a very simple JUnit test to go along with it. The test just runs the example program with one example design (count16.rscp). If no exceptions are thrown, the test will pass.

It could be argued that it is strange to use a JUnit test for something like this, but it is very easy to do. Is this how we want to go about including the example programs as tests? 

If it is, I can start doing the other example programs as well. Some of the other example programs can probably have more in-depth JUnit tests as well. But for some of them (like this one) it is probably sufficient to just run the program and make sure no exceptions are thrown.

### CODE REVIEW

**Comment by DallonTG** [comment]
That's probably a good idea. I can add that in.

The problem with comparing the input and output TCPs is that the formats are actually different. You import a .rscp and export a .tcp. They could still be compared, but it would take moer wor than just a bash command to compare two directories.

**Comment by DallonTG** [comment]
I actually changed a couple of things with this last commit. 

For one, I updated the build.gradle to use the -ea VM option for the JUnit tests. Without this, assertions like the one that are included in the DesignAnaylzer won't be caught by the JUnit tests when you do a gradle build. (So the travis-ci checks will probably fail since the DesignAnalyzer needs a fix pushed for it). I think we will want this enabled for all the tests that are run.

Second, the test now deletes the generated TCP. The code I use is the same as the code in another test that has some temporary files. Going forward, if we have test classes that need similar functionality, should we make a helper test class that contains such methods? This might be something to revist once we finish the upgrade to JUnit5 GA.

**Comment by mcrossen** [comment]
do you know why gradlew.bat is in the diff? they look the same as far as I can tell

**Comment by DallonTG** [comment]
No, I don't know why. I just checked and they are identical.

**Pull request merged**
