### PR TITLE
Set site name only

### PR DESCRIPTION
**Pull request by DallonTG**
The site.setName() method does more than just setting the name; it also populates the X and Y coordinates for the site if the site name includes "_X". 

This is fine, except for when you want to set a site name that includes "_X", but the name doesn't include the true coordinates of the site. I've run into this problem while working on a partial device project, where my site names sometimes include "_X" in the name.

This PR adds a site.setNameOnly() method, where only the site name is set. Really, the setName() method should only do this, but I don't want to break anybody else's code by changing that method.

### CODE REVIEW

**Comment by mcrossen** [comment]
I'd be interested to know the reasoning behind setName() parsing out _X in the first place.

**Comment by trharoldsen** [comment]
Can we change things up so that instead of a setSiteNameOnly method, we move the setting of the XY coordinates to a method like setRPMCoordinates (I think its the RPM grid) or something.  Then the setName would only update the name.  We'd need to update the device generator to immediately call setRPMCoordinates immediately after the setName call, preferably with some level of sanity checking code.

**Comment by DallonTG** [comment]
I added a method called setXYCoordinates(String name). It doesn't seem specific to a RPM grid to me? I could very well be wrong. Also updated the device generator. Not sure what sanity checking code you had in mind for that, but I think what's there now is good.

It's better to just change setName() anyway since it is also called as part of de-serialization (which was giving me grief when it tried to infer the XY coordinates of my oddly named sites that included multiple _X's and _Y's in them).

**Comment by DallonTG** [comment]
Are there changes you still want made? Or can this be merged?

**Comment by trharoldsen** [comment]
I added the suggested updates to this review.

**Pull request merged**
